name: Build on Ubuntu-latest and Deploy on self-hosted

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    environment:
      name: testing

    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_IP_ADDRESS: ${{ secrets.DATABASE_IP_ADDRESS }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Pull git repo
        uses: actions/checkout@v7

      - name: Install Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v

  deploy:
    runs-on: [self-hosted, linux, x64, fastapi-prod]

    needs: [build]

    environment:
      name: production

    steps:
      - name: Show deployment server
        run: |
          hostname
          whoami
          pwd

      - name: Pull latest code
        run: |
          cd /home/fastapi-prod/app
          git pull --rebase origin main

      - name: Install dependencies
        run: |
          cd /home/fastapi-prod/app
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart FastAPI
        run: |
          echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart fastapi.service

      - name: Check FastAPI service
        run: |
          sudo systemctl status fastapi.service --no-pager

      - name: Test FastAPI
        run: |
          curl --fail http://127.0.0.1:8000
